### ISSUE TITLE
`V1HostPathVolumeSource` is not imported into `kubernetes.client`

### ISSUE THREAD

**Issue by seeker89** [kubernetes-incubator/client-python#101]
It does make it to the `kubernetes.client.models` [via this line](https://github.com/kubernetes-incubator/client-python/blob/cd2342dc2e220eff42040f82d4f53f3b5d108cd6/kubernetes/client/models/__init__.py#L98), but then it gets lost in [`kubernetes/client/__init__.py`](https://github.com/kubernetes-incubator/client-python/blob/cd2342dc2e220eff42040f82d4f53f3b5d108cd6/kubernetes/client/__init__.py).

I would submit a PR, but it looks like the code is auto-generated, so it should be fixed somewhere else.

Either way, awesome work @mbohlool, many thanks for that!

**Comment by mbohlool** [comment]
Yes, I need to fix this in a generated way.

**Comment by mbohlool** [comment]
@seeker89 I've sent a PR, would be nice if you can review it.

**Comment by seeker89** [comment]
With pleasure. I'm in GMT, will take care of that in the morning.

**Comment by mbohlool** [comment]
@seeker89 I got LGTM for that PR. I am going to merge it, but feel free to look at it and let me know if you want any change there, and we can send another PR for that.

**Comment by seeker89** [comment]
@mbohlool Works nicely, thanks for the super quick fix 👍

**Comment by mbohlool** [comment]
You are welcome.
