### ISSUE TITLE
Pypi Package name should state it as a client

### ISSUE THREAD

**Issue by codevulture** [kubernetes-incubator/client-python#119]
I think python package name should be changed to some more descriptive name like kubernetes-client or something as kubernetes could be confusing to users.
what are your opinions?

**Comment by mbohlool** [comment]
I think "client" in the inner package name is redundant. It should be as simple as saying "import kubernetes..." to use the client. But I am open to rename the filename (the one that shows up on pypi and install commands) to something else, though it would be a backward incompatible change and could be confusing to some people that are using the client right now. Over all I don't see enough value for this, but I am open for more discussion.

**Comment by codevulture** [comment]
Yes, It would break the backward incompatibility. But from users perspective seemed a different convention. I would leave it upto you to see any possibility.Thanks.

**Comment by gtaylor** [comment]
I think `kubernetes` is fine. This is commonly done with API clients.

**Comment by mbohlool** [comment]
I personally think `kubernetes` is fine too. But anyway, we can't easily change that as it breaks backward compatibility. closing this.
