### ISSUE TITLE
Pip install failing

### ISSUE THREAD

**Issue by prerakpradhan** [kubernetes-incubator/client-python#126]
Currently just running pip install kubernetes but it throws an error saying: 
Downloading/unpacking kubernetes
  Could not find a version that satisfies the requirement kubernetes (from versions: 1.0.0a3, 1.0.0a5, 1.0.0b1, 1.0.0a4, 1.0.0a2, 1.0.0a5, 1.0.0a4, 1.0.0-alpha.2, 1.0.0b1)
Cleaning up...
No distributions matching the version for kubernetes
Storing debug log for failure in /root/.pip/pip.log

Putting in the version, however seems to resolve the issue:
pip install kubernetes==1.0.0b1

Is this a known issue?

**Comment by mbohlool** [comment]
No.

Have you installed the package before? What is your OS/Environment? Could this be something wrong with your installation of python? (easiest way to check that is to use virtualenv)

**Comment by WilliamDenniss** [comment]
I got the same error running `pip install kubernetes` the first time. 

Once I updated pip (`pip install --upgrade pip`), and tried again, it worked. Version 1.0.0b3 was installed in the end.

**Comment by khusanovich** [comment]
I'm trying to install kubectl using pip install kubectl. but it gives an error: 
ERROR: Could not find a version that satisfies the requirement kubectl (from versions: none)
ERROR: No matching distribution found for kubectl

I also updated pip install --upgrade pip, but it didn't help
