### ISSUE TITLE
Move generated readme to /docs

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-incubator/client-python#13]
I would suggest moving the generated README to something like /docs

And make the README.prefix the main README

Otherwise it is a very long file.

It should also containe instructions on how to build the new client

**Comment by mbohlool** [comment]
I've tried different things here. The problem is there are lots of link (and link backs) to main README file. If I rename or move it in any way, I need to fix all of the documentation links. It is not terrible to do, but that is what it takes to move the file.

**Comment by sebgoa** [comment]
To help do this (or future change like this in the future), maybe the munge-docs.sh script in k8s main repo can help.

I do think this needs to happen. The current README is super long, and it looks like if we want to update it we need to actually patch the .prefix and then wait for a rebuild (or rebuild entirely in a PR to change a README...).

I would do it :) Bite the bullet now.

**Comment by mbohlool** [comment]
Cool, thanks. Regarding the rebuild, I think we want the generated code always updated (like other generated codes in k8s). But I agree with you that if there is a better way to do this, we should do it. I will assign the issue to you. Thanks.

**Comment by mbohlool** [comment]
Also, I am not sure how munge-docs.sh works, but now that I think about it, a simple replace  /\.\.README.md/README.md/g for all files in doc folder and moving generated README.md file to doc/ folder (after find/replace) should work.

**Comment by mbohlool** [comment]
I've rearranged things in #31 If that is approved by you, then this issue does not apply anymore (no README.prefix in #31 because the generated client is now in a sub directory)

**Comment by sebgoa** [comment]
great, I think it is much better like this.
