### ISSUE TITLE
setup.py install fail on libyml requirement

### ISSUE THREAD

**Issue by mrmcmuffinz** [kubernetes-incubator/client-python#139]
**Scenario**

Tried to execute `python setup.py install` in virtual environment.

**Output Snippet**
```
Installed /home/acabrer/virtualenvironments/kpclient/lib/python2.7/site-packages/websocket_client-0.40.0-py2.7.egg
Searching for pyyaml
Reading https://pypi.python.org/simple/pyyaml/
Best match: PyYAML 3.12
Downloading https://pypi.python.org/packages/6b/f0/a0250248ea260d55748fff586d89a32afbb22656f4498b08d2636a48d4ec/PyYAML-3.12.zip#md5=aa5e762e79b19bb80dbcf04f82178832
Processing PyYAML-3.12.zip
Writing /tmp/easy_install-74zG5i/PyYAML-3.12/setup.cfg
Running PyYAML-3.12/setup.py -q bdist_egg --dist-dir /tmp/easy_install-74zG5i/PyYAML-3.12/egg-dist-tmp-fFtZo1
build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
compilation terminated.

libyaml is not found or a compiler error: forcing --without-libyaml
(if libyaml is installed correctly, you may need to
 specify the option --include-dirs or uncomment and
 modify the parameter include_dirs in setup.cfg)
zip_safe flag not set; analyzing archive contents...
Moving PyYAML-3.12-py2.7-linux-x86_64.egg to /home/acabrer/virtualenvironments/kpclient/lib/python2.7/site-packages
Adding PyYAML 3.12 to easy-install.pth file
```

**Question**
1. What are the OS packages required to get this working, in my case I'm on Fedora 23?

**Comment by mrmcmuffinz** [comment]
To answer my own question, I think we need to state that inorder to use any of python yml parsers we would need some os level package for it to work. In my case, fedora 23, I would need to install libyml-dev via dnf as such

`sudo dnf install libyaml-devel -y`

And that should silence the above error. **Note**: this step will be different for each OS.

**Comment by mbohlool** [comment]
would you say this is a libyaml problem not ours? or is there a way to prevent this by using another library?

**Comment by mrmcmuffinz** [comment]
I'm leaning towards this being a dependency of `pyyaml` itself and not necessarily client-python. The only thing imho worth noting in the readme is the need of installing the devel package for pyyaml to work depending on the operating system but then again do we really want to go that far? I'm not sure however as a consumer of this api, I know how to get around the issue.
