### ISSUE TITLE
exec response returning with extra data

### ISSUE THREAD

**Issue by mrmcmuffinz** [kubernetes-incubator/client-python#140]
**Scenario**
I'm trying to check if a specific files exists in my pod and assert it on my end using a direct string to string comparison.

**Code Snippet**
```python
cmd = "[ -f /etc/hosts ] && echo 'True' || echo 'False'"
response = kubernetes_client.connect_post_namespaced_pod_exec(pod, kubernetes_namespace, stderr=True, stdin=True, stdout=True, command=cmd, tty=False)
is_file = response.strip()
print is_file
print [ord(c) for c in is_file]
print len(is_file)
```

**Output**
```
True
[1, 1, 84, 114, 117, 101]
6
```

**Problem**
Before in kubernetes v1.0.0.b1, I did not have those extra characters in the beginning of my response but with the latest v1.0.0b3 I do. Anyone know why this is the case?

**Comment by mrmcmuffinz** [comment]
This looks to me like we are packing some extra data in the beginning but I'm not sure. If I do the below modification it works for me.

```python
    response = response[2:]
    found = True if response.strip() == "True" else False
```

Is this related to the peek functions for stdout and stdin?

**Comment by mrmcmuffinz** [comment]
Upon doing some debugging here is what I found.

1. in `def websocket_call` we do 
```python
        try:
            client = WSClient(configuration, url, headers)
            if not _preload_content:
                return client
            client.run_forever(timeout=_request_timeout)
            return WSResponse('%s' % ''.join(client.read_all()))
        except (Exception, KeyboardInterrupt, SystemExit) as e:
```
2. The function `client.run_forever` under the covers runs a `self.update` which will try to append the data coming in from the stream to some local data buffer?
3. We are not verifying if the incoming data is meaningful such that it will tack on the data.

Stack Trace from debugging:
```
(Pdb) l
165  	            if op_code == ABNF.OPCODE_CLOSE:
166  	                self._connected = False
167  	                return
168  	            elif op_code == ABNF.OPCODE_BINARY or op_code == ABNF.OPCODE_TEXT:
169  	                import pdb; pdb.set_trace()
170  ->	                data = frame.data
171  	                if six.PY3:
172  	                    data = data.decode("utf-8")
173  	                self._all += data
174  	                if len(data) > 1:
175  	                    channel = ord(data[0])
(Pdb) n
> /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/kubernetes/client/ws_client.py(171)update()
-> if six.PY3:
(Pdb) n
> /Users/acabrer/virtualenvs/kpclient/lib/python2.7/site-packages/kubernetes/client/ws_client.py(173)update()
-> self._all += data
(Pdb) p data
'\x01'
```

I think we need to add some additional layer of filtering here but not sure what or how... ?

**Comment by mrmcmuffinz** [comment]
I see what the fix is @dims in https://github.com/kubernetes-incubator/client-python/blob/066bba1802797b1d7895854ec6fdb51f5a9d8823/kubernetes/client/ws_client.py#L58 would just truncate that data but @mbohlool looks like we forgot this step above. Could you please fix this?

**Comment by mrmcmuffinz** [comment]
Here is what I did to my local code to _"resolve"_ it
```python
    def update(self, timeout=0):
        """Update channel buffers with at most one complete frame of input."""
    
        if not self.is_open():
            return
        if not self.sock.connected:
            self._connected = False
            return
        r, _, _ = select.select(
            (self.sock.sock, ), (), (), timeout)
        if r:
            op_code, frame = self.sock.recv_data_frame(True)
            if op_code == ABNF.OPCODE_CLOSE:
                self._connected = False
                return
            elif op_code == ABNF.OPCODE_BINARY or op_code == ABNF.OPCODE_TEXT:
                data = frame.data
                if six.PY3:
                    data = data.decode("utf-8")
                if len(data) > 1:
                    channel = ord(data[0])
                    data = data[1:]
                    if data:
                        self._all += data
                        if channel not in self._channels:
                            self._channels[channel] = data
                        else:
                            self._channels[channel] += data
```
I just transposed `self._all = data` a few lines down to not include the channel data.

**Comment by mbohlool** [comment]
That was a conscious choice :) When you call the API in blocking mode, it returns one string. But there could be stderr and stdout in the result and those numbers are channel numbers for stderr and stdout. Having said that, I see what is the problem here. We do not have frame's boundary in the response. The update method gets data in frames and start of each frame is a channel number. But the caller (in blocking mode) does not have those frame boundaries and it is harder to parse stderr and stdout out of the response. Solutions:

1. Blocking call returns stderr and stdout both without channel id.
2. Blocking call returns a map of stderr and stdout (this is arguably a breaking change that we should not do in beta)

With solution one, if you want stdout and stderr, you need to call the api in non-blocking mode (`_preload_content=False`).

I think we go with number 1 for now unless anybody has any objection.

**Comment by mbohlool** [comment]
@mrmcmuffinz Look like what I am proposing is what you have in your comment. do you want to send a PR for that?

**Comment by mbohlool** [comment]
I remove my last two comments as they were confusing. I like @mrmcmuffinz suggestion and I will send a PR for that. Basically what you see was my failed attempt to provide enough information for the caller to distinguish between stderr and stdout. For that, you need to call the api in non-blocking mode (_preload_content=False).
