### ISSUE TITLE
Possibility to create custom objects

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes-incubator/client-python#157]
Can I create custom objects with the python api?

I'm refering to [this](https://kubernetes.io/docs/user-guide/thirdpartyresources/#creating-custom-objects).

**Comment by mbohlool** [comment]
most probably yes. The reason I am guessing that is the client library calls directly into APIs and most of functionality of kubectl should be possible. I suggest you run the create command of kubectl with -v 9 to get the API call and see if you can figure out which/how to call the related API. something like:

```
kubectl create -v 9 -f my-crontab.yaml
```

You can pass a dictionary to python API calls, so if you find the API call, this should work.

**Comment by webwurst** [comment]
I have started on an example to work with third party resources: https://github.com/giantswarm/operator-example-python

I needed to come up with a hack to access the API in a generic way: https://github.com/giantswarm/operator-example-python/blob/master/generic_api.py

@mbohlool What do you think? Is there a better solution?

**Comment by mbohlool** [comment]
Why do you want a generic api call? I did not use third party resources much, but I would try to write an OpenAPI spec for my resource and then generate a client and share base of this client with that. I can look into third party resources support later.

**Comment by mbohlool** [comment]
TPR support is added #5
