### ISSUE TITLE
Add the markdown files from the template project

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-incubator/client-python#16]
There is a template project that is good to follow to include a few basic markdown files:

https://github.com/kubernetes/kubernetes-template-project

**Comment by mbohlool** [comment]
Keeping this issue open until kubernetes/kubernetes-template-project#4 resolved

**Comment by sebgoa** [comment]
honestly , we can close this. I will send you a PR to update the CLA stuff..

**Comment by mbohlool** [comment]
oh, sorry, I didn't see your message and when kubernetes/kubernetes-template-project#4 got approved, I created the PR: #24

**Comment by mbohlool** [comment]
Feel free to assign any of the issues to yourself if you want to work on them. I will label some of them as "help-needed" but honestly, any issue that is not assign to me is open to take :)
