### ISSUE TITLE
Cascading Deployment Removal

### ISSUE THREAD

**Issue by InAnimaTe** [kubernetes-incubator/client-python#162]
When calling `delete_namespaced_deployment`, even with `orphaned_dependents` (which doesn't mean I think it means), *only* the deployment object itself gets removed. This means you've got the ReplicaSet and 1 or more Pods still running.

Between garbage collection and ReplicaSet [references](https://github.com/kubernetes/kubernetes/pull/35676) to the Deployment that created it, there still doesn't seem to be a way to have a `delete` [cascade](https://github.com/kubernetes/kubernetes/issues/34052#issuecomment-251566491) properly. 

Kinda wondering how others are solving the problem and if maybe there needs to be more development in this area either here or upstream. Merely trying to provide a reliable removal function in my application...

**Comment by TracyBin** [comment]
you can call delete replicaset and pod alone against label selector

**Comment by TracyBin** [comment]
sorry,I can't reproduce the problem. when orphaned_dependents=True, replicaset and pods all gets removed

**Comment by TracyBin** [comment]
sorry for wrong reply. you are right.orphaned_dependents takes no effect

**Comment by mbohlool** [comment]
doesn't look like a python client issue. More like an upstream feature request. can you do delete cascade with kubectl? If yes, you can use -v9 with kubectl to see what APIs are called.

**Comment by InAnimaTe** [comment]
On my phone so don't have the link handy but kubectl apparently handles
this itself. I do think you're right in that this is an actual API feature
request more so than a client-python problem.

**Comment by vascofg** [comment]
I'm having this same issue, and after further investigation have found out that the current (1.6.1) way of doing this is with the parameter `propagationPolicy` on the DeleteOptions:
[k8s documentation](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#setting-the-cascading-deletion-policy)

It seems the python client doesn't support this ATM:
[v1_delete_options.py](https://github.com/kubernetes-incubator/client-python/blob/4c3aced24423b7da073f755286b269a9aad2d747/kubernetes/client/models/v1_delete_options.py)

When can we expect this feature to be implemented?

**Comment by mbohlool** [comment]
Can you guys give 2.0.0a a try. I've updated python client.

**Comment by vascofg** [comment]
I've tried it, working fine for my application, at least the new options I needed in [v1_delete_options.py](https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/client/models/v1_delete_options.py) are working fine.

**Comment by djkonro** [comment]
@vascofg ,Please I tried the function call below, but I was still unable to archive cascading deletion. Can you help me understand what I am not doing right?

`extensions.delete_namespaced_deployment(name='nginx-deployment', namespace='default', body=client.V1DeleteOptions(),grace_period_seconds = 56, propagation_policy = \"Background\")`

**Comment by vascofg** [comment]
Check this, there's a bug with background deletion of deployments:
https://github.com/kubernetes/kubernetes/issues/44046
Use foreground for now.

**Comment by djkonro** [comment]
@vascofg, I have also tried `Foreground` but it still deletes only the deployment and not it dependents.

**Comment by vascofg** [comment]
I think your error is when creating DeleteOptions, try passing parameters to the object constructor, mine looks like this:
```
client.V1DeleteOptions(propagation_policy="Foreground", grace_period_seconds=5)
```

Hope it helps

**Comment by djkonro** [comment]
I have tried `extensions.delete_namespaced_deployment(name='nginx-deployment', namespace='default', body=client.V1DeleteOptions(propagation_policy="Foreground", grace_period_seconds=5))`, but I am still getting the same result (pods are not deleted). Thanks alot for the help.

**Comment by vascofg** [comment]
Is the replicaset being deleted?

**Comment by djkonro** [comment]
No, the replicaset not deleted.

**Comment by vascofg** [comment]
What version of Kubernetes are you running? This feature is only supported
since 1.6.0

On Jun 13, 2017 17:38, "Konrad Djimeli" <notifications@github.com> wrote:

No, the replicaset not deleted.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes-incubator/client-python/issues/162#issuecomment-308175921>,
or mute the thread

**Comment by djkonro** [comment]
@vascofg, Thanks very much, I just updated my version for Kubernetes and it now works fine.
