### ISSUE TITLE
Update generated client

### ISSUE THREAD

**Issue by vascofg** [kubernetes-incubator/client-python#167]
I would like to request that you update the generated client for API v1.6.0

**Comment by mbohlool** [comment]
I am working on that. There is a breaking change in definition naming in main repo that most probably will force us to increase major version of the client.

**Comment by vascofg** [comment]
Found out about that when trying to generate the code myself... Best of luck.
Any ETA on the release?

**Comment by mbohlool** [comment]
not yet. I am thinking about renaming models to make them compatible with previous version. To keep track of the semver, I need to get a meaningful diff of specs. Will keep this issue updated.

**Comment by mbohlool** [comment]
I've updated generated client and released 2.0.0a1. Give it a try and let me know if it works (you need to use `--pre` flag with pip to install it).
