### ISSUE TITLE
V1Patch.md is missing

### ISSUE THREAD

**Issue by vedujoshi** [kubernetes-incubator/client-python#173]
The file https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/docs/V1Patch.md is missing

It is referred by https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/docs/CoreV1Api.md#patch_namespace

**Comment by mbohlool** [comment]
dup #117

For patch models, you can just pass a `dict`. This needs documentation.

**Comment by mbohlool** [comment]
related: https://github.com/swagger-api/swagger-codegen/issues/5400

**Comment by TracyBin** [comment]
#187
