### ISSUE TITLE
int-or-string

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-incubator/client-python#18]
support kubernetes custom format "int-or-string".

**Comment by mbohlool** [comment]
I've tried once to fix this. There is a class generated called intStringIntOrString. I've tried to modify that to support custom marshal-unmarshal of json, but the generated apiClient does not make it easy to have custom marshalling. I will take another shot at this when I get time, but feel free to the the issue if you have a solution for it.

**Comment by mbohlool** [comment]
We need a proper fix for IntOrString. assuming it is string is not working because if the server returns an object that has an integer in an IntOrString field, we convert it to string and if we modify object and send it back to server, we get validation error.

**Comment by vedujoshi** [comment]
Can this be fixed soon ?
