### ISSUE TITLE
patch_namespaced_deployment gets 500 as response when using json-patch

### ISSUE THREAD

**Issue by aosterkamp** [kubernetes-incubator/client-python#187]
When using a [RFC6902](https://tools.ietf.org/html/rfc6902)  formatted json-patch you get a 500 response.
The hack for the issue #93 introduced this bug. 
Are there any plans to get rid of the hack?

To repoduce the problem the following can be done:

create the deployment with kubectl 
```bash
kubectl run nginx --image=nginx:1.11.12
```

try to patch it
```python
from kubernetes import client, config
config.load_kube_config()
client.configuration.debug = True
v1 = client.ExtensionsV1beta1Api()
patch = [{"op": "replace", "value": "nginx:1.11.13", "path": "/spec/template/spec/containers/0/image"}]
v1.patch_namespaced_deployment(name='nginx', namespace='default', body=patch)
```

log output
```
DEBUG Starting new HTTPS connection (1): xxx
send: b'PATCH /apis/extensions/v1beta1/namespaces/default/deployments/nginx HTTP/1.1\r\nHost: xxx\r\nAccept-Encoding: identity\r\nContent-Length: 95\r\nAccept: application/json\r\nContent-Type: application/strategic-merge-patch+json\r\nUser-Agent: Swagger-Codegen/1.0.0-alpha/python\r\nauthorization: Bearer xxx\r\n\r\n'
send: b'[{"op": "replace", "value": "nginx:1.11.13", "path": "/spec/template/spec/containers/0/image"}]'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'
DEBUG https://xxx:443 "PATCH /apis/extensions/v1beta1/namespaces/default/deployments/nginx HTTP/1.1" 500 114
header: Content-Type header: Date header: Content-Length Traceback (most recent call last):
  File "api_test.py", line 25, in <module>
    main()
  File "api_test.py", line 21, in main
    print(v1.patch_namespaced_deployment(name='nginx', namespace='default', body=patch_test))
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 5400, in patch_namespaced_deployment
    (data) = self.patch_namespaced_deployment_with_http_info(name, namespace, body, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/extensions_v1beta1_api.py", line 5496, in patch_namespaced_deployment_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 329, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 153, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 399, in request
    body=body)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 295, in PATCH
    body=body)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Fri, 21 Apr 2017 12:05:35 GMT', 'Content-Length': '114'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Invalid JSON document","code":500}
```

**Comment by mbohlool** [comment]
patch should be an object not an array of objects.

```python
patch = {"op": "replace", "value": "nginx:1.11.13", "path": "/spec/template/spec/containers/0/image"}
```

**Comment by aosterkamp** [comment]
as the RFC states it is an list of objects

```
  [
     { "op": "test", "path": "/a/b/c", "value": "foo" },
     { "op": "remove", "path": "/a/b/c" },
     { "op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ] },
     { "op": "replace", "path": "/a/b/c", "value": 42 },
     { "op": "move", "from": "/a/b/c", "path": "/a/b/d" },
     { "op": "copy", "from": "/a/b/d", "path": "/a/b/e" }
   ]
```

if you mean that the api responses with a 200, when you patch just an object, yes you're right, but the patch is not applied.

if you comment out lines 150 and 151 in  kubernetes/client/rest.py it works again. So the content-type in this case is wrong.

**Comment by mbohlool** [comment]
@dims added those lines. @dims can the content type removed from header? or can we fix it to work with this case?

**Comment by dims** [comment]
@mbohlool : ack, i'll try to find a way to multiple ways to specify the patch request body
https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#patch-operations

**Comment by TracyBin** [comment]
```python
body = client.V1beta1Deployment(api_version='extensions/v1beta1', kind='Deployment',
                                    metadata=metadata, spec=spec, status=status)

   # call API
try:
        ext_v1_client.patch_namespaced_deployment(name=deployment_name, namespace=deployment_namespace, body=body, pretty='true')
except ApiException as e:
   
```

**Comment by mbohlool** [comment]
I think this is fixed? please re-open if it is not fixed.

**Comment by chlung** [comment]
@aosterkamp If I would like to update multiple values from your above example
  [
     { "op": "replace", "path": "/a/b/c", "value": 42 },
     { "op": "replace", "path": "/a/b/d", "value": 43 }
   ]
Is it above correct?  Can I do something like the following?  Thanks
[
  { "op": "replace",
    "something": [
      { "path": "/a/b/c", "value": 42},
      { "path": "/a/b/d", "value": 43}
    ]
  }
]

**Comment by aosterkamp** [comment]
@chlung sorry for the late reply.

your first example is correct. The second one should not work as far as the RFC goes, but I haven't tested it.

**Comment by chlung** [comment]
@aosterkamp thanks

**Comment by DjangoPeng** [comment]
@mbohlool Does the issue fixed? I faced the same issue. Could you help have a look at my case?
I'd like to update replicas of deployment, which like the operation of `kubectl scale --replicas deployment/xxx`.  So, I made a patch like this `patch = {"spec": {"replicas": desired_replicas}}`, and desired_replicas is a parameter which I would assign. I attached my code as below:
```
api_instance = client.ExtensionsV1beta1Api()
name = cccccx-11404185
namespace = "default"
patch = {"spec": {"replicas": 3}}
api_response = api_instance.patch_namespaced_deployment(name, namespace, patch)
```
The output as below:
```
kubernetes.client.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 17 Aug 2017 03:06:21 GMT', 'Content-Length': '117', 'Content-Type': 'application/json'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"unrecognized type: int32","code":500}
```
If I set the replicas as `0`, it works. I don't know what's wrong with my patch.

**Comment by mbohlool** [comment]
I would run `kubectl -v9` with that command and look at json object it send to server and also enable debug here (to see the same thing) and compare them. There is a `debug` flag in `configuration` class but make sure you set it before creating the client.

**Comment by DjangoPeng** [comment]
@mbohlool I made a plan b to scale deployment, which as below:
1. Load the yaml file and get the body.
2. Set `body['spec']['replicas'] = desired_replicas` .
3. Call `replace_namespaced_deployment(name, namespace, body)` .

**Comment by mbohlool** [comment]
Be very careful about `replace_namespaced_deployment` specially when the client talks with clusters that has a version ahead of them. There would be dropped fields and unknown behaviours. We are making some designs to fix that, but till then, using replace is not recommended. I would spend a little more time figuring our the patch. I know people had problem with it if you search issues and the answer were always a slice formatting issue in the body of patch.

**Comment by DjangoPeng** [comment]
@mbohlool Ok, look forward to your PR. Thanks!

**Comment by mbohlool** [comment]
I don't think a PR here helps. What I am suggesting is to fix your problem, you can change the format of the patch to match what server expect. Other users of the client already figured that out and by searching into the issues, you can find your solution. Good luck and let me know if you need any help there.

**Comment by TracyBin** [comment]
The patch object doesn't work at all, the following code is wrong
``` 
#patch = [{"op": "remove", "path": "/spec/template/spec/containers/0/volume_mounts"}]
    patch = {"spec": {"/spec/template/spec/volumes/0/persistent_volume_claim": None}}
    try:
        response = ext_v1_client.patch_namespaced_deployment(name=name, namespace=namespace, body=patch,
                                                             pretty='true')
        print(response)
    except ApiException as e:
        pass
```
@DjangoPeng  Yours method is right
