### ISSUE TITLE
Release 2.0 Stable

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-incubator/client-python#204]
All of the issues with v2.0 milestone mark has been resolved. I've released 2.0.0b1 today and will just wait 1 week to make sure people have time to give it a try and report any problem with it. If no serious bug found, will release 2.0.0b1 as 2.0.0 stable as is.

**Comment by gtaylor** [comment]
How are we looking?

**Comment by mbohlool** [comment]
I forgot to close the issue, sorry. The release is done. Let me know if you have any problem with it.
