### ISSUE TITLE
TypeError: urlopen() got multiple values for keyword argument 'body' ON patch_namespaced_deployement

### ISSUE THREAD

**Issue by arrkaye** [kubernetes-incubator/client-python#214]
With the call "patch_namespaced_deployment('service', 'default', 'hello')" on AppsV1beta1Api()

I get the below error. Am I doing something wrong here? 

> Traceback (most recent call last):
>   File "deploy.py", line 26, in <module>
>     v1.patch_namespaced_deployment(d[3], 'default', 'hello')
>   File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/apps_v1beta1_api.py", line 1550, in patch_namespaced_deployment
>     (data) = self.patch_namespaced_deployment_with_http_info(name, namespace, body, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/kubernetes/client/apis/apps_v1beta1_api.py", line 1646, in patch_namespaced_deployment_with_http_info
>     collection_formats=collection_formats)
>   File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 329, in call_api
>     _return_http_data_only, collection_formats, _preload_content, _request_timeout)
>   File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 153, in __call_api
>     _request_timeout=_request_timeout)
>   File "/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 399, in request
>     body=body)
>   File "/usr/local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 295, in PATCH
>     body=body)
>   File "/usr/local/lib/python2.7/site-packages/kubernetes/client/rest.py", line 166, in request
>     headers=headers)
>   File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 78, in request
>     **urlopen_kw)
>   File "/usr/lib/python2.7/dist-packages/urllib3/request.py", line 141, in request_encode_body
>     **urlopen_kw)
> TypeError: urlopen() got multiple values for keyword argument 'body'

**Comment by riazkarim** [comment]
I get the same error when specifying the path op:

` v1.patch_namespaced_deployment(d[3], "default", {"op": "replace", "path":"/spec/template/spec/containers/0/image", "value":Url})`

**Comment by mbohlool** [comment]
what is your `kubernetes` and `urllib3` version?

**Comment by arrkaye** [comment]
urllib3 (1.8.2)
kubernetes (2.0.0-snapshot)

**Comment by mbohlool** [comment]
your urllib3 is old. see here: https://github.com/kubernetes-incubator/client-python/blob/master/requirements.txt

**Comment by pastet89** [comment]
@mbohlool You state that @arrkaye 's urllib3 version is old. He states the has a version of 1.8.2 and you point him to a link requiring 1.19.1. Would you please clear that? I have just upgraded mine and got:

`Package python-urllib3:                 
p   1.9.1-3                                       oldstable                 500 
i   1.16-1+deb8u1                                 oldstable                 500 

Package python-urllib3-whl:
p   1.9.1-3                                       oldstable                 500 

Package python3-urllib3:
i A 1.9.1-3                                       oldstable                 500 `

but still can't resolve this error.
