### ISSUE TITLE
Authentication issue for new list third party resource endpoint

### ISSUE THREAD

**Issue by pvdvreede** [kubernetes-incubator/client-python#227]
Hi @mbohlool I am trying the new tpr resources endpoints and it seems to work fine if I am outside a cluster, but when I run it in a cluster it appears that my call to `list_third_party_resource` is getting a 401 as there is no auth passed with the request. This is in contrast to the `replace_third_party_resource` call which seems to work fine.

I did notice that here: https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/client/apis/third_party_resources_api.py#L487, there is no 'Bearer' in the auth settings like there appears to be in the replace call I do elsewhere.

Is there some configuration on the client generation that is missing?

Thanks.

**Comment by mbohlool** [comment]
It is a bug in the original tpr spec. I've fixed it in #230. Please review it.
