### ISSUE TITLE
Looping Symlinks

### ISSUE THREAD

**Issue by codevulture** [kubernetes-incubator/client-python#232]
For tracking purpose logging an issue.
There 2 recursive links:

~/client-python/kubernetes$ ll watch
lrwxrwxrwx 1 ubuntu ubuntu 10 May 18 08:25 watch -> base/watch/
~/client-python/kubernetes$ ll base/watch/
lrwxrwxrwx 1 ubuntu ubuntu  5 May 18 08:25 watch -> watch

[Lopping Symlinks](https://github.com/kubernetes-client/python-base/commit/3b44c3b6a98b1f04dfcfee63e46f959858c350df) patch closes this.
Thanks.

**Comment by pokoli** [comment]
AFAIU this issue can be closes as the looping symlinks is commited. Am I missing something?
