### ISSUE TITLE
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected key users in kube-config

### ISSUE THREAD

**Issue by sidd14491** [kubernetes-incubator/client-python#236]
After installing Kubernets package used the script to list of all pods.
But After running the script I am observing following error.
  File "1.py", line 4, in <module>
    config.load_kube_config()
  File "build/bdist.linux-x86_64/egg/kubernetes/config/kube_config.py", line 311, in load_kube_config
  File "build/bdist.linux-x86_64/egg/kubernetes/config/kube_config.py", line 282, in _get_kube_config_loader_for_yaml_file
  File "build/bdist.linux-x86_64/egg/kubernetes/config/kube_config.py", line 118, in __init__
  File "build/bdist.linux-x86_64/egg/kubernetes/config/kube_config.py", line 134, in set_active_context
  File "build/bdist.linux-x86_64/egg/kubernetes/config/kube_config.py", line 253, in __getitem__
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected key users in kube-config

**Comment by mbohlool** [comment]
does `kubectl` works? can you share redacted kube config file content at `~/.kube/config`?

**Comment by sidd14491** [comment]
apiVersion: v1
clusters:
- cluster:
    server: http://10.213.18.39:8080
  name: test
contexts:
- context:
    cluster: test
    user: test
  name: test
Yes Kubectl command is working fine
Below the o/p of command
root@csp-central-ms-vm1839:~/REQUESTS# kubectl get pods
NAME                                          READY     STATUS             RESTARTS   AGE
csp.admin-portal-ui-346402271-qnuw8           1/1       Running            0          24d
csp.ams-2611059999-cypjx                      1/1       Running            0
    24d

**Comment by pokoli** [comment]
I uploaded a PR that should fix this issue, could you test please?

**Comment by mbohlool** [comment]
I commented on your (merged) PR. I think it is in the right direction but needs more fixes. It may fix @sidd14491 issue (sidd14491 can you confirm?) but need to fix this for all cases where user is missing.

**Comment by sidd14491** [comment]
For verification which build I need to take. 
Can you mention the build location from where I'll take the fixed version and tested my scenario..
Thanks.
Siddharth

**Comment by pokoli** [comment]
You have to install the latest version from sources. The following commands will do:

```
git clone --recursive git@github.com:kubernetes-incubator/client-python.git
cd client-python/kubernetes/base
git checkout master
cd ../..
python setup.py install
```

Then you can execute an example script with your client config. The following command will load the default context of your kube.cfg:

`python -m examples.example1`

**Comment by pokoli** [comment]
@mbohlool before closing this PR I think that we must update the git submodule to a revision that includes all the fixes. What do you think?

**Comment by mbohlool** [comment]
Definitely. Go for it.

**Comment by pokoli** [comment]
I'm waiting for kubernetes-client/python-base#5 to be merged before updating submodules.

For now we should keep the issue open. Can you reopen please?

**Comment by sidd14491** [comment]
Hi,
 I have one query,
Is there any rest-api in kubernetes to upgrade the container build with
specific on.
Suppose that I want to upgrade from 212 to 214, but I want pass the 214 as
a argument in rest call with specific pods

BR/
Siddharth

**Comment by pokoli** [comment]
@sidd14491 I don't see how your question is related to the current thread. Can you open a new issue please?

**Comment by sidd14491** [comment]
Hi
 It's not related to current bug I am just asking you query is there any to
do that ?

BR?
Siddharth

**Comment by pokoli** [comment]
So please open a new issue for different questions....

**Comment by scottprichard** [comment]
of course this is closed.
