### ISSUE TITLE
Bug in ThirdPartyResourcesApi (hardcoded resource path)

### ISSUE THREAD

**Issue by ebbeelsborg** [kubernetes-incubator/client-python#256]
This project is awesome and I was delighted to see #216 get merged.

There is a bug when constructing the resource paths, however: For instance, in the class ThirdPartyResourcesApi, on line 126 (+/-):

resource_path = '/apis/{fqdn}/v1/namespaces/{namespace}/{resource}'.replace('{format}', 'json')

This does not work for third-party resources which are not of version 'v1' exactly. So, for example, the apiVersion "monitoring.coreos.com/v1alpha1" fails with a 404.

I suggest taking in the version as a formal parameter in the relevant methods and injecting it in the resource path.

**Comment by mbohlool** [comment]
The definition is in https://github.com/kubernetes-incubator/client-python/blob/master/scripts/thirdpartypaths.json

If you are up to it, just edit it and run update-client (I suggest run it before change to make sure it is only your changes in that generation).

**Comment by mbohlool** [comment]
```python
from kubernetes import config
config.load_incluster_config()
...
```
