### ISSUE TITLE
ThirdPartyResourcesApi.delete_third_party_resource()

### ISSUE THREAD

**Issue by djmckinley** [kubernetes-incubator/client-python#280]
I've been trying to use the ThirdPartyResourcesApi class to manage instances of our third party resources, and it all seems to work nicely except for the delete_third_party_resource() function.  Here, the code (kubernetes/client/apis/third_party_resources_api.py) has it defined as: `def delete_third_party_resource(self, body, **kwargs)`, with "body" described as a "V1DeleteOptions" type.

It is not clear how to specify the identify of the resource to be deleted.  I would expect parameters like you have with get or update - i.e., name, namespace, fqdn, version, and resource.

Is this a problem?  Or is the identify of the object to be deleted to be descrbed in the 'body' parameter somehow?  I've experimented with it some, but without success.  Also, reading the code, it looks like it is expecting those parameters to be defined, though they are not.

I installed the library from the source with setup.py, using the commit made on June 25 (7650c9a)

**Comment by mbohlool** [comment]
Look like we should make those parameters as shared parameter here: https://github.com/kubernetes-incubator/client-python/blob/master/scripts/thirdpartypaths.json#L107

instead of defining them for each operation (and hence missed them for delete operation).
