### ISSUE TITLE
Timeout_seconds  within list_namespace function does not work

### ISSUE THREAD

**Issue by TracyBin** [kubernetes-incubator/client-python#294]
hi,
   I want to watch timeout when the call time is over timeout_seconds,but it does not work
  ```
v1_client.list_namespace(watch=False, timeout_seconds=2)
 ```

**Comment by mbohlool** [comment]
`timeout_seconds=2` is only meaningful if you are watching an object. To watch an object see watch example and see if timeout works there.

**Comment by TracyBin** [comment]
@mbohlool  OK,Thank you

**Comment by fjolublar** [comment]
@mbohlool 
>timeout_seconds=2 is only meaningful if you are watching an object. 

Should this be fixed in the documentation? I had assumed the `timeout_seconds` is the total request timeout
