### ISSUE TITLE
PR from original repo

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-incubator/client-python#3]
Hi, I had made a PR to your original repo before it moved.

https://github.com/mbohlool/k8s-clients/pull/2

I guess you want me to move the PR here ?

**Comment by mbohlool** [comment]
Sure, the walkthrough needs some updates though. For example, after PR #2 merged, a proxy is not required, the client should be able to read kube config and work with the active configuration that kubectl is working with.

**Comment by sebgoa** [comment]
Have you tried without a proxy on a SSL+auth endpoint ?

I am asking because it does not seem to work. I get a connection refused.

**Comment by mbohlool** [comment]
on branch o2, it should work with ssl+auth.

**Comment by sebgoa** [comment]
I tested the 02 branch and it works. So I will just close this and wait for the merge.
I can help with better README etc after the merge.
