### ISSUE TITLE
kubernetes.ThirdPartyResources() does not exist while the Doc saying so.

### ISSUE THREAD

**Issue by SongGithub** [kubernetes-incubator/client-python#306]
I was following the [Doc here](https://github.com/kubernetes-incubator/client-python/blob/master/examples/create_thirdparty_resource.md). However, when I run `api_instance = kubernetes.ThirdPartyResources()`, error says `AttributeError: module 'kubernetes' has no attribute 'ThirdPartyResources'`.

So: 
- Can you guys correct the doc? 
- BTW, where can I find an API to list objects within a TPR?

**Comment by mbohlool** [comment]
dup of #274?

**Comment by zoidbergwill** [comment]
I think they're related, but separate issues. Was that class removed?

**Comment by zoidbergwill** [comment]
Is it gonna be replaced by Custom Resource Definitions stuff?

**Comment by mbohlool** [comment]
Yes, use https://github.com/kubernetes-incubator/client-python/tree/master/kubernetes/client/apis#L27

It is a matter of definition, but I think this is still a duplicated of #274. To make the example runnable, we need to fix it to use this class. I am going to close this. Please reopen if that is not the case.

**Comment by zoidbergwill** [comment]
Awesome, thanks. :+1:
