### ISSUE TITLE
No __version__ information

### ISSUE THREAD

**Issue by brejoc** [kubernetes-incubator/client-python#317]
Sometimes it could be useful to get the version information programmatically, just like Django is doing it for example. There you can get the version string via `django.__version__`.

This is especially helpful, if your program requires `kubernetes` and is fine with either version, but needs to distinguish between the different APIs `kubernetes` offers.

**Comment by mbohlool** [comment]
Looks like a good idea, adding help needed label for somebody to pick it up. Should be a simple change.
