### ISSUE TITLE
[Feature request]cascading delete deployment

### ISSUE THREAD

**Issue by DjangoPeng** [kubernetes-incubator/client-python#320]
When I call `delete_namespaced_deployment()` method, I find that the corresponding replicaSet and Pod are not removed. The same issue was submitted on `client-go` project [here](https://github.com/kubernetes/client-go/issues/50). I'm not sure if there is a way to do the cascading deletion. If yes, where and how to use it? If not, do you have plan to make it?

**Comment by DjangoPeng** [comment]
I found there is a same issue [here](https://github.com/kubernetes-incubator/client-python/issues/162). According to the discussion, I summaries the usage of cascading deletion:
1. You need to set the `propagation_policy='Foreground'` when instantiate `client.V1DeleteOptions()`.
2. Kubernetes version 1.6+.
```
# Example 
api_instance = client.ExtensionsV1beta1Api()
api_response = api_instance.delete_namespaced_deployment(name, namespace, client.V1DeleteOptions(propagation_policy='Foreground', grace_period_seconds=5))
```
In a word, I think we would like update the usage of this API in the documents.

**Comment by mbohlool** [comment]
Nice, it may worth creating an example or a doc/how-to for this, so other people can benefit from it.

**Comment by DjangoPeng** [comment]
@mbohlool I'd like to make a PR for that tonight.

**Comment by mbohlool** [comment]
@DjangoPeng I appreciate it.

**Comment by DjangoPeng** [comment]
@mbohlool Sorry for a leave. Today, I'm trying to create a PR to add a usage example of cascading deletion. I wanna ensure is it right to add the example [here](https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/client/apis/extensions_v1beta1_api.py#L2025).

**Comment by mbohlool** [comment]
Examples should be added to /example folder at the root of the repo.

**Comment by DjangoPeng** [comment]
I find a [usage of deployment](https://github.com/kubernetes-incubator/client-python/blob/master/examples/notebooks/create_deployment.ipynb) in the /example/notebooks folder. Would you mind me adding a `deployment_examples.py` in the /example folder? I think it's better to merge the [create_deployment.py](https://github.com/kubernetes-incubator/client-python/blob/master/examples/create_deployment.py) into it.

**Comment by mbohlool** [comment]
More examples are good so go ahead with deployment_examples.py.
