### ISSUE TITLE
Deleting namespaced deployment returns with code=None

### ISSUE THREAD

**Issue by brejoc** [kubernetes-incubator/client-python#327]
When invoking [delete_namespaced_deployment_with_http_info()](https://github.com/kubernetes-incubator/client-python/blob/release-1.0/kubernetes/client/apis/extensions_v1beta1_api.py#L2359), the response looks like this:

```
{'api_version': 'extensions/v1beta1',
 'code': None,
 'details': None,
 'kind': 'Deployment',
 'message': None,
 'metadata': {'resource_version': '6894440',
              'self_link': '/apis/extensions/v1beta1/namespaces/default/deployments/my-nginx'},
 'reason': None,
 'status': "{u'observedGeneration': 1}"}
```

The deployment is successfully removed from the Kubernetes cluster, but the return code is `None`. @flavio mentioned in flavio/salt-kubernetes-demo/issues/1 that this is due the fact that this is an async operation internally.

How should we treat those cases? Is a `None` return code intended here? How do we know, that the request finally succeeded?

Tested with version 1.0.2 and 2.0.0.

**Comment by brejoc** [comment]
Okay, [reading the docs](http://kubernetes.readthedocs.io/en/stable/kubernetes.client.apis.html?highlight=delete_namespaced_deployment_with_http_info#kubernetes.client.apis.apps_v1beta1_api.AppsV1beta1Api.delete_namespaced_deployment_with_http_info) actually helps. I'm closing this this issue.

> delete a Deployment This method makes a synchronous HTTP request by default. To make an asynchronous HTTP request, please define a callback function to be invoked when receiving the response.

**Comment by tomplus** [comment]
@brejoc Unfortunately a callback doesn't help you. It will get the same structure. Deleting deployment can take a lot of time (stopping and deleting all replicasets). To be sure if deployment has been deleted you have to try to get it again. If it doesn't exist you will get error - not found.

**Comment by brejoc** [comment]
@tomplus Okay, thanks for the heads-up.

**Comment by brejoc** [comment]
@tomplus Do you know if there is something like an event bus I'd be able to subscribe to? Thx!

**Comment by tomplus** [comment]
@brejoc Probably you can watch the method `list_namespaced_deployment`. You will get the event DELETE "immediately before deletion" (https://kubernetes.io/docs/api-reference/v1.7/#watchevent-v1-meta). I've not tested it yet.

**Comment by mbohlool** [comment]
Yes watch is the way to go.  https://github.com/kubernetes-incubator/client-python/blob/master/examples/example2.py

**Comment by brejoc** [comment]
@tomplus @mbohlool That sounds awesome. Thanks guys!
