### ISSUE TITLE
1.0.0-alpha Release

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-incubator/client-python#33]
To get the client adapted more, I plan to do a ~~0.1.0~~ 1.0.0-alpha release and push it to pypi.
Pre-release:
- [x] in-cluster config support #32
- [x] rename package to kubernetes #31

release items:
- [x] github release tag
- [x] Pypi push (automated on releases somehow?)

**Comment by sebgoa** [comment]
could you check that #36 is fixed (or that I am doing it wrong) before cutting a release ?

**Comment by mbohlool** [comment]
That is working for me, we can always cherry pick a fix if there is a bug or even create a new release as this is an alpha release.

**Comment by mbohlool** [comment]
discussed this with @lavalamp, decided to go for 1.0.0-alpha instead of 0.1.0 as the interface is pretty stable and we don't expect it to change much.
