### ISSUE TITLE
setup.py does not install kubernetes.stream module

### ISSUE THREAD

**Issue by larsks** [kubernetes-incubator/client-python#355]
The `setup.py` file in the distribution currently contains:

    packages=['kubernetes', 'kubernetes.client', 'kubernetes.config',
              'kubernetes.watch', 'kubernetes.client.apis',
              'kubernetes.client.models'],

This is missing an entry for `kubernetes.stream`, which means that if you install the client and try running [this example](https://github.com/kubernetes-incubator/client-python#example), you get:

```
Traceback (most recent call last):
  File "watcher.py", line 1, in <module>
    from kubernetes import client, config, watch
  File "/usr/lib/python2.7/site-packages/kubernetes/__init__.py", line 22, in <module>
    import kubernetes.stream
ImportError: No module named stream

```

**Comment by mbohlool** [comment]
Good catch.

**Comment by larsks** [comment]
Glad to help.  A couple of quick questions:

- Is there any reason not to use `find_packages` here instead of listing packages individually?
- Shouldn't this have been caught by CI since it broke `import kubernetes`?
