### ISSUE TITLE
PyPI source distribution missing requirements.txt

### ISSUE THREAD

**Issue by allanadair** [kubernetes-incubator/client-python#361]
setup.py depends on the presence of requirements.txt and test-requirements.txt, however these files are not included within the source distribution on PyPI.

This means that the package cannot be installed from the source distribution.

**Comment by Ajay191191** [comment]
I can confirm this. setup.py fails to install because of the absence of those 2 files.

**Comment by mbohlool** [comment]
@allanadair Thanks for reporting this. If you know a quick fix for this, I appreciate it if you send a PR for it.
