### ISSUE TITLE
recommended slack channel

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-incubator/client-python#37]
is there recommended slack channel API-machinery or should we ask to create a dedicated one ?

**Comment by mbohlool** [comment]
I think we can continue using api-machinery slack channel until we got disruptive there. @lavalamp?

**Comment by lavalamp** [comment]
Sounds fine to me!

**Comment by SEJeff** [comment]
Can that be in the [README](README.md) as the official channel to use?

**Comment by mbohlool** [comment]
It is there right now.
