### ISSUE TITLE
How to run client inside POD

### ISSUE THREAD

**Issue by AssafKatz3** [kubernetes-incubator/client-python#405]
There is no example which it is equvivelent to [Accessing the API from a Pod of go client](https://github.com/kubernetes/client-go/blob/master/examples/in-cluster-client-configuration/main.go). This will be benefit for who want to run such script without building full software (for example, running script during HELM hook).

**Comment by tomplus** [comment]
Hi @AssafKatz3, this example is quite similar [examples/in_cluster_config.py](https://github.com/kubernetes-incubator/client-python/blob/master/examples/in_cluster_config.py).

**Comment by AssafKatz3** [comment]
I checked three times and missed it. Thanks

**Comment by tomplus** [comment]
No worries.
