### ISSUE TITLE
connect_get_namespaced_pod_portforward and connect_post_namespaced_pod_portforward not working

### ISSUE THREAD

**Issue by vfreex** [kubernetes-incubator/client-python#417]
Sample code:
``` python
resp = v1api.connect_post_namespaced_pod_portforward(
            test_pod.metadata.name, test_pod.metadata.namespace,
            ports=8080,
            _request_timeout=60,
            _preload_content=False
        )
```
`HTTP 400 Upgrade request required` is returned from the API server.
```
E           kubernetes.client.rest.ApiException: (400)
E           Reason: Bad Request
E           HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-store', 'Content-Type': 'application/json', 'Date': 'Wed, 13 Dec 2017 08:22:09 GMT', 'Content-Length': '139'})
E           HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}\n'

/home/vfreex/.local/lib/python3.6/site-packages/kubernetes/client/rest.py:240: ApiException
```

**Comment by mbohlool** [comment]
please look at https://github.com/kubernetes-incubator/client-python/blob/master/examples/exec.py

**Comment by Ark-kun** [comment]
> please look at https://github.com/kubernetes-incubator/client-python/blob/master/examples/exec.py

stream only works for UTF-8 output. Anything else crashes it.

**Comment by marielb** [comment]
I'm getting the same `HTTP 400 Upgrade request required` response without using stream.

With stream, `connect_post_namespaced_pod_exec` works but `connect_post_namespaced_pod_portforward` returns this API exception:`Reason: 'utf-8' codec can't decode byte 0xc0 in position 1: invalid start byte`

**Comment by maloochpich** [comment]
This issue is still there, the example @mbohlool is sharing is for exec not for 
connect_post_namespaced_pod_portforward

**Comment by mpluhar** [comment]
+1 same issue here

**Comment by tusharsappal** [comment]
+1 the issue is still there , can some one please have a look and resolve it ASAP

**Comment by micw523** [comment]
AFAIK port forward is not supported on this client yet. The Python client is a [silver](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/csi-new-client-library-procedure.md#client-capabilities) client.

**Comment by MRostanski** [comment]
@mbohlool Why did you close this without any helpful comment? What does that mean "please look at"? The example given is about exec, not about portforward... I have the same problem and the link does NOT help at all.

**Comment by dims** [comment]
As this is a open source project, can the folks interested in this issue organize themselves to fix this issue and open a PR? Looks like there is lot of interest. It would help the overloaded existing maintainers for sure.

**Comment by karmab** [comment]
not working here either, here's the sample code i tried to use

```
from kubernetes import client, config
from kubernetes.stream import stream

podname = "xxx-aaaa"
namespace = "demo"
localport = 52501

config.load_kube_config()
core = client.CoreV1Api()

resp = stream(core.connect_get_namespaced_pod_portforward, podname, namespace, ports=localport,
              _request_timeout=60, _preload_content=False)
print(resp.read_stdout())
```

**Comment by ilovemysillybanana** [comment]
did anyone ever get this working?

**Comment by dgethings** [comment]
> AFAIK port forward is not supported on this client yet. The Python client is a [silver](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/csi-new-client-library-procedure.md#client-capabilities) client.

@micw523 Thank you for this helpful answer. I too believe this is the root of why this feature does not work in the python client.

**Comment by reinvantveer** [comment]
Hope this is still of help: I got something working from the example at https://github.com/kubernetes-client/python/blob/master/examples/pod_portforward.py#L97

It's pretty low-level (especially from a Python point of view) but it appears to work very well. There's some more work involved if you want to inspect the response headers as well (you'd have to use `api_instance.connect_get_namespaced_pod_portforward_with_http_info` instead if I would hazard a guess)

**Comment by reinvantveer** [comment]
> 
> 
> > please look at https://github.com/kubernetes-incubator/client-python/blob/master/examples/exec.py
> 
> stream only works for UTF-8 output. Anything else crashes it.

I included an updated link to one supplied by @Ark-kun : since the Python client appears to have left incubator status

**Comment by reinvantveer** [comment]
@Ark-kun could you perhaps update your answer to include the updated link? It's much higher up the thread, so it's more visible to other users.
