### ISSUE TITLE
ThirdParty resources support 

### ISSUE THREAD

**Issue by sebgoa** [kubernetes-incubator/client-python#5]
If we create a 3rd party resource, it creates a new API group.

I am not sure how kubectl implements it, but we need to have an example on how to do this with this client.

For example, say I create a 3rd party resource called snake. In kubectl I can do:

```
kubectl get snakes
```

It dynamically learns of new resources in new API groups.

**Comment by mbohlool** [comment]
A possible solution could be having k8sutil.Resource(name=...) class that support k8s resources such as pods, service, etc. as well as third party resources.

**Comment by mbohlool** [comment]
dup of #201. closing this one.
