### ISSUE TITLE
Support API calls with no json response

### ISSUE THREAD

**Issue by mbohlool** [kubernetes-incubator/client-python#55]
Some of the calls like logs does support json and text response but there is no way to get the text response as the generated client automatically select json as the accepted response. One example of this is kubernetes/kubernetes#37881. The workaround in that issue is working (and shows the value of _preload_content we added to generated code) but we can do better by having a solution like Watch class to get response as text and even stream the result if the call supports it. In this case read_namespaced_pod_log supports streaming but the parameter is named follow not watch.

Possible Solution:

```python
v1 = client.CoreV1Api()
# either:
raw = kubernetes.raw_response.RawResponse(v1.read_namespaced_pod_log, 
    namespace="...", name="...")
raw.read()

# or
raw = kubernetes.raw_response.RawResponse(v1.read_namespaced_pod_log, 
    namespace="...", name="...", follow=True)
for line in raw.stream():
   print(line)
```

**Comment by quasiben** [comment]
Yes, this is essentially what I was doing with a hacked version of the `api_client.py` and `default_api.py`.  Added a `raw` argument and returned the *raw* Response object back from the request

**Comment by mbohlool** [comment]
As a workaround for now, you can pass ```_preload_content=False``` to the api call, then call ```.read()``` method on the return object. for example:

```
    v1 = client.CoreV1Api()
    ret = v1.read_namespaced_pod_log(
        "kube-addon-manager-minikube", "kube-system", _preload_content=False)
    print(ret.read())
```

**Comment by mbohlool** [comment]
kubernetes/kubernetes#37881 is fixed, after we updated the client, this will be not necessary.
