### ISSUE TITLE
`read_namespaced_pod_log` get None response

### ISSUE THREAD

**Issue by yejw5** [kubernetes-incubator/client-python#57]
When I use `kubectl logs ms-999-near-090248-357595620-lze7r`, I can get container log messages. But the following code get response with None message:
```
import os
from kubernetes import client, config
# Configs can be set in Configuration class directly or using helper utility
config.load_kube_config(os.environ["HOME"] + '/.kube/config')

def callback_func(response):
  print(response)

api = client.CoreV1Api()
api.read_namespaced_pod_log("ms-999-near-090248-357595620-lze7r", "default", callback=callback_func)
```
The exec result is:
```
{'metadata': None, 'spec': None, 'status': None}
```
Is this way to call `read_namespaced_pod_log` not appropriate？

**Comment by mbohlool** [comment]
It is a known issue #55 You can find a workaround there.

**Comment by yejw5** [comment]
@mbohlool Many thanks! The method solves this problem properly.
