### ISSUE TITLE
`stat: can't specify None for path argument` when loading config from GKE cluster

### ISSUE THREAD

**Issue by paultiplady** [kubernetes-incubator/client-python#77]
The client appears to be unable to parse authentication information from GKE clusters.

The exception is being raised here: https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/config/kube_config.py#L185, when `_load_cluster_info` expects there to be a `client-certificate` key in the user dictionary.

With the `GKE` provider, my config looks like this:

```
{'auth-provider': {'name': 'gcp', 'config': {'expiry': datetime.datetime(2016, 12, 27, 22, 18, 24, 911838), 'access-token': '<redacted>'}}}
```

I also had to fix this in pykube, as follows: https://github.com/kelproject/pykube/pull/67/files. Would you accept a fix along those lines here too?

Here is the full stack trace:

```
Traceback (most recent call last):
  File "dns_controller.py", line 17, in <module>
    main()
  File "dns_controller.py", line 6, in main
    config.load_kube_config()
  File "/Users/paul/.virtualenvs/dns-controller/lib/python3.5/site-packages/kubernetes/config/kube_config.py", line 297, in load_kube_config
    client_configuration=client_configuration).load_and_set()
  File "/Users/paul/.virtualenvs/dns-controller/lib/python3.5/site-packages/kubernetes/config/kube_config.py", line 203, in load_and_set
    self._load_cluster_info()
  File "/Users/paul/.virtualenvs/dns-controller/lib/python3.5/site-packages/kubernetes/config/kube_config.py", line 187, in _load_cluster_info
    file_base_path=self._config_base_path).as_file()
  File "/Users/paul/.virtualenvs/dns-controller/lib/python3.5/site-packages/kubernetes/config/kube_config.py", line 82, in as_file
    if not os.path.isfile(self._file):
  File "/Users/paul/.virtualenvs/dns-controller/bin/../lib/python3.5/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: can't specify None for path argument
```

**Comment by mbohlool** [comment]
the pykube fix you mentioned does not apply here. Look like we are correctly reading gcp token here: https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/config/kube_config.py#L150

But assumption that if the host starts with https, the config file will always have cert_file, ssl_cert_file, and key_file may not be true. The correct patch here is to make those optional (set them if they exists).

**Comment by mbohlool** [comment]
if you just change line 82 from:

```python
if not os.path.isfile(self._file):
```

to

```python
if self._file and not os.path.isfile(self._file):
```

it should work. do you want to give it a try?

**Comment by mbohlool** [comment]
Well, look like there is another bug, I will send a patch.

**Comment by mbohlool** [comment]
I've send the fix. As this look urgent (config loader does not work for GKE, GCE or any other cluster with token authorization), I will do another alpha release with the fix.

**Comment by mbohlool** [comment]
Please update your package to 1.0.0a4 and try again. It should work.

**Comment by paultiplady** [comment]
That's working now. Thanks for the quick turnaround!
