### ISSUE TITLE
Another same project [ https://github.com/openstack/python-k8sclient ] , We should check it out to avoid duplicate efforts for both :)

### ISSUE THREAD

**Issue by codevulture** [kubernetes-incubator/client-python#87]

**Comment by mbohlool** [comment]
Thanks for reporting this. I've looked at that project (and many other python clients) before. The reason that we decided to start this project is that we didn't found any up to date supported client for python. They are either not actively developed, not up to date with latest changes of kubernetes or does not have good tooling around them to make them useful.

This project (client-python) is generated from new spec plus tools around it to make it useful (watch support, kube-config support, etc.). It is also a supported/maintained client (by kubernetes api machinery team).

For this specific client you mentioned, It is not generated from the latest spec (released in 1.5). It is using outdated spec (swagger 1.2, outdated here means both spec and the content of the spec file). Also that is a complete generated code without any tooling around it. Please let me know if I missed something.

I am completely open to any contribution from the community or other python clients.

**Comment by stibi** [comment]
@mbohlool thanks for your work here on the client-python. It's really the only one working Python client for Kubernetes. I have a lot of use for it in my AWS Lambda functions :)

**Comment by mbohlool** [comment]
Thanks @stibi. 

@codevulture I am closing this issue, please feel free to reopen, if my reply was not satisfying.

**Comment by codevulture** [comment]
Thanks for your comment, I think we will start using this client soon :) , I will push a couple of patches soon to minimize the differences and later move to using this client.
Thanks for your work!
