### ISSUE TITLE
What needs to be done to get patch_namespaced_deployment to work?

### ISSUE THREAD

**Issue by rwillard** [kubernetes-incubator/client-python#93]
I want to update the image for one of my containers in a deployment and it seems I can't provide an UnversionedPatch. Using a valid JSON patch string, or the strategic-merge string I use in kubectl ends up with variations of 
```HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"json: cannot unmarshal string into Go value of type jsonpatch.Patch","code":500}```

Am I doing something wrong or is this not implemented yet? The link to UnversionedPatch returns a 404 https://github.com/kubernetes-incubator/client-python/blob/master/kubernetes/docs/UnversionedPatch.md If it's not implemented I'd be happy to work on it.

**Comment by mbohlool** [comment]
Look like Patch is defined as this in kubernetes:

```go
// Patch is provided to give a concrete name and type to the Kubernetes PATCH request body.
type Patch struct{}
```
That I hoped would result in an empty class in generated code, but it look like swagger-codegen ignores it (it exists in swagger.json). I guess we may need to implement it manually. If you want to work on it, that's great. Add the class to kubernetes/client/model but keep in mind that the folder will be removed and regenerated on each call to scripts/update-client.go so make sure you update the script to keep your file somewhere and restore it. We may need to have a general mechanism for this non-generated codes inside generated packages.

**Comment by dims** [comment]
@mbohlool @rwillard - patch_namespaced_service and patch_namespaced_config_map have the same problem. I am adding functional tests against a real k8s instance in my PR here:
https://github.com/kubernetes-incubator/client-python/pull/94/commits/8fac5fe38d53ba86417b9f2b2417b2d1bc0c848f

**Comment by mbohlool** [comment]
@rwillard can you please confirm if you are working on this?

**Comment by mbohlool** [comment]
no problem. Thanks for letting us know.
